name: Node.js CI

on:
  push:
    branches:
      - "spa"
  pull_request:
    branches:
      - "spa"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Run npm ci
        run: npm ci

      - name: Run npm build
        run: npm run build
